# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  google_api_key: <%= ENV['GOOGLE_API_KEY'] %>

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c5342d8803d19541f4b40a2a70bbdde8bcb2028fb4bdd41fd5a0fe27f3325a08b85b3df0da5dce7fb938ce8b3b3ce638171c495d5c48d25941b9a0f185a898a4

test:
  secret_key_base: 60595991b6e52ecd58570210ee3d0922fda4b97c20ff5cac6ef192bea18758e5a9c3243b15a1e7266553c4fcbddef627584975865c2f447ea664a77668c0bb55

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
